import numpy as np
import cv2

CANNY_THRESHOLD1 = 100
CANNY_THRESHOLD2 = 200

MIN_LINE_LENGHT_COEFF = 0.75

HOUGH_RHO = 1
HOUGH_THETA = np.pi / 180

VERTICAL_TAN_MIN = 50
HORIZONTAL_TAN_MAX = 0.02

MIN_DIST = 15

HOUGH_LOW_THRESHOLD = 50
HOUGH_THRESHOLD_STEP = 15

MIN_EDGE_COEFF = 0.25

METHOD = cv2.HOUGH_GRADIENT
DP = 2
PARAM1 = 200

MIN_INTERSECTION_DIST_COEFF = 0.3

WHITE_THRESHOLD = 250
BLACK_THRESHOLD = 5

MIN_BOARD_SIZE_COEFF = 0.1